name: Containerise and run UI code
on:
  push:
    branches:
      - main

jobs:
  ui:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Build image
        run: COMPOSE_BAKE=true ORIGIN=https://houseplant-hub-api.glen-sharp.uk docker compose build
      - name: Run container
        run: docker compose up -d
